title = "The Red Orchard"
base_url = "https://impeccableshoddy.github.io/"
generate_feeds = true
compile_sass = false
build_search_index = false

[markdown]

[markdown.highlighting]
highlight_code = true
theme = "solarized-light"
style = "class"
code_filenames = true
line_numbers = true

highlighting_themes_css = [
  { theme = "solarized-light", filename = "giallo.css" }
]

[extra]
